CREATE TABLE `tax_intake_submissions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`taxYear` int NOT NULL,
	`firstName` varchar(64),
	`middleInitial` varchar(4),
	`lastName` varchar(64),
	`email` varchar(128),
	`phone` varchar(32),
	`dateOfBirth` varchar(16),
	`ssnLast4` varchar(4),
	`streetAddress` varchar(256),
	`aptSuite` varchar(64),
	`city` varchar(64),
	`state` varchar(2),
	`zip` varchar(10),
	`filingStatus2` enum('single','married_jointly','married_separately','head_of_household','qualifying_widow'),
	`spouseFirstName` varchar(64),
	`spouseLastName` varchar(64),
	`spouseDob` varchar(16),
	`spouseSsnLast4` varchar(4),
	`dependents` json,
	`incomeDocs` json,
	`deductions` json,
	`donations` json,
	`additionalNotes` varchar(2000),
	`intakeStatus` enum('draft','submitted','in_review','ready_to_sign','filed') DEFAULT 'draft',
	`paymentType` enum('free_consult','basic_filing'),
	`stripePaymentIntentId` varchar(128),
	`aiReviewNotes` text,
	`preparerNotes` text,
	`intakeCreatedAt` timestamp NOT NULL DEFAULT (now()),
	`intakeUpdatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `tax_intake_submissions_id` PRIMARY KEY(`id`)
);
